services:
  - type: web
    name: myr-laravel
    env: docker
    plan: free
    autoDeploy: true
    buildFilter:
      paths:
        - Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://myr-hkfx.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: ballast.proxy.rlwy.net
      - key: DB_PORT
        value: 45764
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: lEsQYNMoPbZHmfPtfmkxiBZSMzsiAZAh
      - key: CLOUDINARY_URL
        value: cloudinary://851329353156846:Axg3QRvdOl4v_nX17vq4RtPISWQ@dtwtippni
